In [1]:
with open('input.txt') as f:
    lines = f.readlines()

In [2]:
lines

['1977\n',
 '1802\n',
 '1856\n',
 '1309\n',
 '2003\n',
 '1854\n',
 '1898\n',
 '1862\n',
 '1857\n',
 '542\n',
 '1616\n',
 '1599\n',
 '1628\n',
 '1511\n',
 '1848\n',
 '1623\n',
 '1959\n',
 '1693\n',
 '1444\n',
 '1211\n',
 '1551\n',
 '1399\n',
 '1855\n',
 '1538\n',
 '1869\n',
 '1664\n',
 '1719\n',
 '1241\n',
 '1875\n',
 '1733\n',
 '1547\n',
 '1813\n',
 '1531\n',
 '1773\n',
 '624\n',
 '1336\n',
 '1897\n',
 '1179\n',
 '1258\n',
 '1205\n',
 '1727\n',
 '1364\n',
 '1957\n',
 '540\n',
 '1970\n',
 '1273\n',
 '1621\n',
 '1964\n',
 '1723\n',
 '1699\n',
 '1847\n',
 '1249\n',
 '1254\n',
 '1644\n',
 '1449\n',
 '1794\n',
 '1797\n',
 '1713\n',
 '1534\n',
 '1202\n',
 '1951\n',
 '1598\n',
 '1926\n',
 '1865\n',
 '1294\n',
 '1893\n',
 '1641\n',
 '1325\n',
 '1432\n',
 '1960\n',
 '413\n',
 '1517\n',
 '1724\n',
 '1715\n',
 '1458\n',
 '1775\n',
 '1317\n',
 '1694\n',
 '1484\n',
 '1840\n',
 '1999\n',
 '1811\n',
 '1578\n',
 '1658\n',
 '1906\n',
 '1481\n',
 '1313\n',
 '1997\n',
 '1339\n',
 '1592\n',
 '1971\n',
 '1453\n',
 '1706\n',
 '1884\n',
 '1956\n',
 '1384\n',
 '1579\n',
 '1689\n',
 '1726\n',
 '1217\n',
 '1796\n',
 '1536\n',
 '1213\n',
 '1867\n',
 '1304\n',
 '2010\n',
 '1503\n',
 '1665\n',
 '1361\n',
 '814\n',
 '2007\n',
 '1430\n',
 '1625\n',
 '1958\n',
 '860\n',
 '1799\n',
 '1942\n',
 '1876\n',
 '1772\n',
 '1198\n',
 '1221\n',
 '1814\n',
 '1826\n',
 '1667\n',
 '1334\n',
 '1504\n',
 '1420\n',
 '1164\n',
 '1414\n',
 '1934\n',
 '1823\n',
 '1507\n',
 '1195\n',
 '21\n',
 '1752\n',
 '1472\n',
 '1196\n',
 '1558\n',
 '1322\n',
 '1927\n',
 '1556\n',
 '1922\n',
 '277\n',
 '1828\n',
 '1883\n',
 '1280\n',
 '1947\n',
 '1231\n',
 '1915\n',
 '1235\n',
 '1961\n',
 '1494\n',
 '1324\n',
 '2009\n',
 '1367\n',
 '1545\n',
 '1736\n',
 '1575\n',
 '1214\n',
 '1704\n',
 '1833\n',
 '1663\n',
 '1474\n',
 '1894\n',
 '1754\n',
 '1564\n',
 '1321\n',
 '1119\n',
 '1975\n',
 '1987\n',
 '1873\n',
 '1834\n',
 '1686\n',
 '1574\n',
 '1505\n',
 '1656\n',
 '1688\n',
 '1896\n',
 '1982\n',
 '1554\n',
 '1990\n',
 '1902\n',
 '1859\n',
 '1293\n',
 '1739\n',
 '1282\n',
 '1889\n',
 '1981\n',
 '1283\n',
 '1687\n',
 '1220\n',
 '1443\n',
 '1409\n',
 '1252\n',
 '1506\n',
 '1742\n',
 '1319\n',
 '1882\n',
 '951\n',
 '1849\n']

In [3]:
numbers = [int(line) for line in lines]
numbers

[1977,
 1802,
 1856,
 1309,
 2003,
 1854,
 1898,
 1862,
 1857,
 542,
 1616,
 1599,
 1628,
 1511,
 1848,
 1623,
 1959,
 1693,
 1444,
 1211,
 1551,
 1399,
 1855,
 1538,
 1869,
 1664,
 1719,
 1241,
 1875,
 1733,
 1547,
 1813,
 1531,
 1773,
 624,
 1336,
 1897,
 1179,
 1258,
 1205,
 1727,
 1364,
 1957,
 540,
 1970,
 1273,
 1621,
 1964,
 1723,
 1699,
 1847,
 1249,
 1254,
 1644,
 1449,
 1794,
 1797,
 1713,
 1534,
 1202,
 1951,
 1598,
 1926,
 1865,
 1294,
 1893,
 1641,
 1325,
 1432,
 1960,
 413,
 1517,
 1724,
 1715,
 1458,
 1775,
 1317,
 1694,
 1484,
 1840,
 1999,
 1811,
 1578,
 1658,
 1906,
 1481,
 1313,
 1997,
 1339,
 1592,
 1971,
 1453,
 1706,
 1884,
 1956,
 1384,
 1579,
 1689,
 1726,
 1217,
 1796,
 1536,
 1213,
 1867,
 1304,
 2010,
 1503,
 1665,
 1361,
 814,
 2007,
 1430,
 1625,
 1958,
 860,
 1799,
 1942,
 1876,
 1772,
 1198,
 1221,
 1814,
 1826,
 1667,
 1334,
 1504,
 1420,
 1164,
 1414,
 1934,
 1823,
 1507,
 1195,
 21,
 1752,
 1472,
 1196,
 1558,
 1322,
 1927,
 1556,
 1922,
 277,
 1828,
 1883,
 1280,
 1947,
 1231,
 1915,
 1235,
 1961,
 1494,
 1324,
 2009,
 1367,
 1545,
 1736,
 1575,
 1214,
 1704,
 1833,
 1663,
 1474,
 1894,
 1754,
 1564,
 1321,
 1119,
 1975,
 1987,
 1873,
 1834,
 1686,
 1574,
 1505,
 1656,
 1688,
 1896,
 1982,
 1554,
 1990,
 1902,
 1859,
 1293,
 1739,
 1282,
 1889,
 1981,
 1283,
 1687,
 1220,
 1443,
 1409,
 1252,
 1506,
 1742,
 1319,
 1882,
 951,
 1849]

In [4]:
# Part 1 - Brute force
for i in numbers:
    for j in numbers:
        if i + j == 2020:
            print(i, j, i*j)

1999 21 41979
21 1999 41979

In [5]:
# Part 2 - Brute force
for i in numbers:
    for j in numbers:
        for k in numbers:
            if i + j + k == 2020:
                print(i, j, k, i*j*k)

624 277 1119 193416912
624 1119 277 193416912
277 624 1119 193416912
277 1119 624 193416912
1119 624 277 193416912
1119 277 624 193416912